SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE TABLE IF NOT EXISTS `legacy_achievements` (
  `bkey` smallint(5) unsigned NOT NULL,
  `name` varchar(20) NOT NULL,
  `descr` tinytext NOT NULL,
  `imagefilename` varchar(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `legacy_achievements` (`bkey`, `name`, `descr`, `imagefilename`) VALUES
(1, 'Visit to the top', 'being at the first place regionally once', ''),
(2, 'I am so lucky', 'won 7 matches in a row', ''),
(4, 'Invincible', 'no deaths with over then 10 kills in a match', ''),
(8, 'GOD MODE', 'no deaths with over then 25 kills in a match', '');

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_claninvites` (
  `clanid` mediumint(8) unsigned NOT NULL,
  `uid` mediumint(8) unsigned NOT NULL,
  KEY `clanid` (`clanid`,`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_clans` (
  `clanid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `tag` varchar(10) NOT NULL,
  `admin` mediumint(8) unsigned NOT NULL,
  `site` varchar(255) NOT NULL,
  `score` float NOT NULL DEFAULT '100',
  `victories` smallint(5) unsigned NOT NULL,
  `defeats` smallint(5) unsigned NOT NULL,
  `draws` smallint(5) unsigned NOT NULL,
  PRIMARY KEY (`clanid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_config` (
  `cfg` varchar(60) NOT NULL,
  `val` varchar(255) NOT NULL,
  PRIMARY KEY (`cfg`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `legacy_config` (`cfg`, `val`) VALUES
('last_update', '1280482570');

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_countries` (
  `id` int(11) unsigned NOT NULL COMMENT 'Country unique identifier',
  `code` varchar(2) DEFAULT NULL,
  `name` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `CODE_UNIQUE` (`code`),
  UNIQUE KEY `NAME_UNIQUE` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `legacy_countries` (`id`, `code`, `name`) VALUES
(1, '__', 'Not selected'),
(2, 'af', 'Afghanistan'),
(4, 'al', 'Albania'),
(5, 'dz', 'Algeria'),
(6, 'as', 'American Samoa'),
(7, 'ad', 'Andorra'),
(8, 'ao', 'Angola'),
(9, 'ai', 'Anguilla'),
(10, 'aq', 'Antarctica'),
(11, 'ag', 'Antigua and Barbuda'),
(13, 'ar', 'Argentina'),
(14, 'am', 'Armenia'),
(15, 'aw', 'Aruba'),
(16, 'au', 'Australia'),
(17, 'at', 'Austria'),
(18, 'az', 'Azerbaijan'),
(19, 'bs', 'Bahamas'),
(20, 'bh', 'Bahrain'),
(21, 'bd', 'Bangladesh'),
(22, 'bb', 'Barbados'),
(23, 'by', 'Belarus'),
(24, 'be', 'Belgium'),
(25, 'bz', 'Belize'),
(26, 'bj', 'Benin'),
(27, 'bm', 'Bermuda'),
(28, 'bt', 'Bhutan'),
(29, 'bo', 'Bolivia'),
(30, 'ba', 'Bosnia and Herzegovina'),
(31, 'bw', 'Botswana'),
(32, 'br', 'Brazil'),
(33, 'bn', 'Brunei Darussalam'),
(34, 'bg', 'Bulgaria'),
(35, 'bf', 'Burkina Faso'),
(36, 'bi', 'Burundi'),
(39, 'kh', 'Cambodja'),
(40, 'cm', 'Cameroon'),
(41, 'ca', 'Canada'),
(42, 'cv', 'Cape Verde'),
(43, 'ky', 'Cayman Islands'),
(44, 'cf', 'Central African Republic'),
(45, 'td', 'Chad'),
(46, 'cl', 'Chile'),
(47, 'cn', 'China'),
(48, 'co', 'Colombia'),
(50, 'km', 'Comoros'),
(51, 'cg', 'Congo, Republic of'),
(52, 'cd', 'Congo, Democratic Republic of'),
(53, 'ck', 'Cook Islands'),
(54, 'cr', 'Costa Rica'),
(55, 'ci', 'Cote d''Ivoire'),
(56, 'hr', 'Croatia'),
(57, 'cu', 'Cuba'),
(58, 'cy', 'Cyprus'),
(59, 'cz', 'Czech Republic'),
(60, 'dk', 'Denmark'),
(61, 'dj', 'Djibouti'),
(62, 'dm', 'Dominica'),
(63, 'do', 'Dominican Republic'),
(64, 'eg', 'Egypt'),
(65, 'sv', 'El Salvador'),
(67, 'ec', 'Equador'),
(68, 'gq', 'Equatorial Guinea'),
(69, 'er', 'Eritrea'),
(70, 'ee', 'Estonia'),
(71, 'et', 'Ethiopia'),
(72, 'eu', 'European Union'),
(73, 'fo', 'Faroe Islands'),
(74, 'fj', 'Fiji'),
(75, 'fi', 'Finland'),
(76, 'fr', 'France'),
(77, 'ga', 'Gabon'),
(78, 'gm', 'Gambia'),
(79, 'ge', 'Georgia'),
(80, 'de', 'Germany'),
(81, 'gh', 'Ghana'),
(82, 'gi', 'Gibraltar'),
(83, 'gr', 'Greece'),
(84, 'gl', 'Greenland'),
(85, 'gd', 'Grenada'),
(86, 'gp', 'Guadeloupe'),
(87, 'gu', 'Guam'),
(88, 'gt', 'Guatemala'),
(90, 'gw', 'Guinea-Bissau'),
(91, 'gn', 'Guinea'),
(92, 'gy', 'Guyana'),
(93, 'ht', 'Haiti'),
(94, 'hn', 'Honduras'),
(95, 'hk', 'Hong Kong'),
(96, 'hu', 'Hungary'),
(97, 'is', 'Iceland'),
(98, 'in', 'India'),
(99, 'id', 'Indonesia'),
(100, 'ir', 'Iran, Islamic Republic of'),
(101, 'iq', 'Iraq'),
(102, 'ie', 'Ireland'),
(105, 'il', 'Israel'),
(106, 'it', 'Italy'),
(107, 'jm', 'Jamaica'),
(108, 'jp', 'Japan'),
(110, 'jo', 'Jordan'),
(111, 'kz', 'Kazakhstan'),
(112, 'ke', 'Kenya'),
(113, 'ki', 'Kiribati'),
(114, 'ko', 'Kosovo'),
(115, 'ku', 'Kuwait'),
(116, 'kg', 'Kyrgyzstan'),
(117, 'la', 'Lao People''s Democratic Republic'),
(118, 'lv', 'Latvia'),
(119, 'lb', 'Lebanon'),
(120, 'ls', 'Lesotho'),
(121, 'lr', 'Liberia'),
(122, 'ly', 'Libyan Arab Jamahiriya'),
(123, 'li', 'Liechtenstein'),
(124, 'lt', 'Lithuania'),
(125, 'lu', 'Luxembourg'),
(126, 'mo', 'Macau'),
(127, 'mk', 'Macedonia'),
(128, 'mg', 'Madagascar'),
(129, 'mw', 'Malawi'),
(130, 'my', 'Malaysia'),
(131, 'mv', 'Maldives'),
(132, 'ml', 'Mali'),
(133, 'mt', 'Malta'),
(134, 'mh', 'Marshall Islands'),
(135, 'mq', 'Martinique'),
(136, 'mr', 'Mauritania'),
(137, 'mu', 'Mauritius'),
(138, 'mx', 'Mexico'),
(139, 'fm', 'Micronesia'),
(140, 'md', 'Moldova'),
(141, 'mc', 'Monaco'),
(142, 'mn', 'Mongolia'),
(144, 'ms', 'Montserrat'),
(145, 'ma', 'Morocco'),
(146, 'mz', 'Mozambique'),
(147, 'mm', 'Myanmar'),
(149, 'na', 'Namibia'),
(150, 'nr', 'Nauru'),
(151, 'np', 'Nepal'),
(152, 'an', 'Netherlands Antilles'),
(153, 'nl', 'Netherlands'),
(154, 'nc', 'New Caledonia'),
(155, 'nz', 'New Zealand'),
(156, 'ni', 'Nicaragua'),
(157, 'ne', 'Niger'),
(158, 'ng', 'Nigeria'),
(159, 'kp', 'North Korea'),
(162, 'no', 'Norway'),
(165, 'om', 'Oman'),
(166, 'pk', 'Pakistan'),
(167, 'pw', 'Palau'),
(168, 'ps', 'Palestine'),
(169, 'pa', 'Panama'),
(170, 'pg', 'Papua New Guinea'),
(171, 'py', 'Paraguay'),
(172, 'pe', 'Peru'),
(173, 'ph', 'Philippines'),
(174, 'pn', 'Poland'),
(175, 'pt', 'Portugal'),
(176, 'pr', 'Puerto Rico'),
(177, 'qa', 'Qatar'),
(179, 're', 'Reunion'),
(180, 'ro', 'Romania'),
(181, 'ru', 'Russian Federation'),
(182, 'rw', 'Rwanda'),
(183, 'lc', 'Saint Lucia'),
(184, 'ws', 'Samoa'),
(185, 'sm', 'San Marino'),
(186, 'st', 'Sao Tome and Principe'),
(187, 'sa', 'Saudi Arabia'),
(189, 'sn', 'Senegal'),
(190, 'cs', 'Serbia'),
(191, 'sc', 'Seyshelles'),
(192, 'sl', 'Sierra Leone'),
(193, 'sg', 'Singapore'),
(194, 'sk', 'Slovakia'),
(195, 'si', 'Slovenia'),
(196, 'sb', 'Solomon Islands'),
(197, 'so', 'Somalia'),
(199, 'za', 'South Africa'),
(200, 'kr', 'South Korea'),
(201, 'es', 'Spain'),
(202, 'lk', 'Sri Lanka'),
(205, 'sd', 'Sudan'),
(206, 'sr', 'Suriname'),
(207, 'sz', 'Swaziland'),
(208, 'se', 'Sweden'),
(209, 'ch', 'Switzerland'),
(210, 'sy', 'Syria'),
(211, 'pf', 'Tahiti (French Polinesia)'),
(212, 'tw', 'Taiwan'),
(213, 'tj', 'Tajikistan'),
(214, 'tz', 'Tanzania'),
(215, 'th', 'Thailand'),
(216, 'tl', 'Timor-Leste'),
(217, 'tg', 'Togo'),
(218, 'to', 'Tonga'),
(219, 'tt', 'Trinidad and Tobago'),
(220, 'tn', 'Tunisia'),
(221, 'tr', 'Turkey'),
(222, 'tm', 'Turkmenistan'),
(223, 'tc', 'Turks and Caicos Islands'),
(224, 'tv', 'Tuvalu'),
(225, 'ug', 'Uganda'),
(226, 'ua', 'Ukraine'),
(227, 'ae', 'United Arab Emirates'),
(228, 'gb', 'United Kingdom'),
(230, 'us', 'United States of America'),
(231, 'uy', 'Uruguay'),
(232, 'uz', 'Uzbekistan'),
(233, 'vu', 'Vanuatu'),
(234, 'va', 'Vatican City'),
(235, 've', 'Venezuela'),
(236, 'vn', 'Viet Nam'),
(237, 'vg', 'Virgin Islands British'),
(238, 'vi', 'Virgin Islands US'),
(240, 'eh', 'Western Sahara'),
(241, 'ye', 'Yemen'),
(242, 'zm', 'Zambia'),
(243, 'zw', 'Zimbabwe');

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_friends` (
  `id1` smallint(5) unsigned NOT NULL,
  `id2` smallint(5) unsigned NOT NULL,
  `accepted` tinyint(4) NOT NULL,
  `1sees2` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `2sees1` tinyint(1) unsigned NOT NULL DEFAULT '1',
  UNIQUE KEY `id1_2` (`id1`,`id2`),
  KEY `id1` (`id1`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_maps` (
  `mid` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `author` varchar(20) NOT NULL,
  `name` varchar(25) NOT NULL,
  `filename` varchar(50) NOT NULL,
  `description` varchar(75) NOT NULL,
  `approved` tinyint(1) NOT NULL DEFAULT '0',
  `rating` decimal(10,0) NOT NULL,
  `uploader` mediumint(8) unsigned NOT NULL COMMENT 'the id of the uploading user',
  `upload_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `dimension` float NOT NULL,
  `checksum` varchar(32) NOT NULL,
  `approvedby` mediumint(8) unsigned NOT NULL,
  `gametype` enum('Normal','Koth','Soccer','Domination','Runners','Russurection','Funny','Stupid','CHP') NOT NULL,
  `size` enum('small','medium','large','huge') NOT NULL,
  PRIMARY KEY (`mid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_players` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Users ID',
  `accountname` varchar(20) NOT NULL COMMENT 'Users account name',
  `pass` varchar(32) NOT NULL COMMENT 'Passwored hashed in md5 wiouth salt',
  `region` enum('eu','na','au','ru','other','sa') NOT NULL COMMENT 'Players geographic region. Don''t forget to edit mysql.php if you want to add another region.',
  `country` tinyint(3) unsigned NOT NULL COMMENT 'country id according the countries table',
  `clan` smallint(5) unsigned NOT NULL COMMENT 'clan ID according to clans table',
  `server_name` varchar(150) NOT NULL COMMENT 'Server name the player is currently on',
  `location` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Players location: 0 offline, 1 in game, 2 on the site, 3 in game. NOT SURE ABOUT IT, check the babo sources',
  `last_update` bigint(20) unsigned NOT NULL COMMENT 'The last time player''s status has been changed',
  `server_ip` varchar(15) NOT NULL COMMENT 'The ip of the server the player is currently on',
  `server_port` smallint(4) unsigned NOT NULL,
  `last_site_visit` int(10) unsigned NOT NULL,
  `last_stats_drop` int(10) unsigned NOT NULL DEFAULT '0',
  `last_used_ip` varchar(15) NOT NULL,
  `last_used_nick` varchar(25) NOT NULL,
  `showoffline` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT 'Does the player want to see his offline friends in the friends list in game? 1 show the offline friends, 0 - don''t show',
  `inmapteam` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Is allowed to aprove maps or not',
  PRIMARY KEY (`id`),
  KEY `accountname` (`accountname`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `legacy_stats` (
  `uid` bigint(8) unsigned NOT NULL,
  `rating` float NOT NULL,
  `time` float unsigned NOT NULL DEFAULT '0',
  `kills` bigint(8) NOT NULL DEFAULT '0',
  `deaths` bigint(8) unsigned NOT NULL DEFAULT '0',
  `damage` float unsigned NOT NULL DEFAULT '0',
  `caps` bigint(8) unsigned NOT NULL DEFAULT '0',
  `returns` bigint(8) unsigned NOT NULL DEFAULT '0',
  `attempts` bigint(8) unsigned NOT NULL DEFAULT '0',
  `userbartitle` varchar(20) NOT NULL,
  `userbarrank` mediumint(8) unsigned NOT NULL,
  `regionaluserbarrank` mediumint(8) unsigned NOT NULL,
  `last_update` int(10) unsigned NOT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
